### ISSUE TITLE
definition of done milestone

### ISSUE THREAD

**Issue by silvaelton** [silvaelton/entherm_core#5]
Deploy version 1.0

> definition of done

# backend

- [ ] module purcharse: stock
- [ ] module purcharse: patriomy
- [ ] module purcharse: improvements in orders
- [ ] module purcharse: reports
- [ ] module purcahse: improvements in dashboard
- [ ] module financial: bills
- [ ] module financial: vencibles
- [ ] module financial: cash registry
- [ ] module financial: bill_categories
- [ ] module financial: reports
- [ ] module financial: dashboard
- [ ] module core: alerts
- [ ] module core: permissions

# front-end

- [ ] improvement background
- [ ] add turbolinks
- [ ] improvement logo of company
- [ ] improvement color in tables
- [ ] improvement placeholder in forms
- [ ] improvement messages :success and :danger 

# infraestructure 

- [ ] amazon S3 upload files
- [ ] delivery e-mails
- [ ] update database to $9

# business

- [ ] contract of maintenance
- [ ] policy of backups
- [ ] professional customer communication
